default_agent: strands_wa_sec_0918
agents:
  strands_wa_sec:
    name: strands_wa_sec
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::384612698411:role/cloud-optimization-assistant-bedrock-agentcore-runtime-role
      execution_role_auto_create: true
      account: '384612698411'
      region: us-east-1
      ecr_repository: 384612698411.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_wa_sec
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_wa_sec-y2k06Q3LeR
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:384612698411:runtime/strands_wa_sec-y2k06Q3LeR
      agent_session_id: 5f535858-836b-4e78-93da-e5db7c07069a
    codebuild:
      project_name: bedrock-agentcore-strands_wa_sec-builder
      execution_role: arn:aws:iam::384612698411:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-67ab493663
      source_bucket: bedrock-agentcore-codebuild-sources-384612698411-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
  strands_wa_sec_0918:
    name: strands_wa_sec_0918
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::384612698411:role/cloud-optimization-assistant-bedrock-agentcore-runtime-role
      execution_role_auto_create: true
      account: '384612698411'
      region: us-east-1
      ecr_repository: 384612698411.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_wa_sec_0918
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_wa_sec_0918-Lkc74b32Yg
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:384612698411:runtime/strands_wa_sec_0918-Lkc74b32Yg
      agent_session_id: b7c7a345-7566-4fd5-93b4-a32001c2f194
    codebuild:
      project_name: bedrock-agentcore-strands_wa_sec_0918-builder
      execution_role: arn:aws:iam::384612698411:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-581498271d
      source_bucket: bedrock-agentcore-codebuild-sources-384612698411-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
