default_agent: aws_billing_cost_opt
agents:
  strands_wa_sec:
    name: strands_wa_sec
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::384612698411:role/cloud-optimization-assistant-bedrock-agentcore-runtime-role
      execution_role_auto_create: true
      account: '384612698411'
      region: us-east-1
      ecr_repository: 384612698411.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_wa_sec
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_wa_sec-y2k06Q3LeR
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:384612698411:runtime/strands_wa_sec-y2k06Q3LeR
      agent_session_id: 5f535858-836b-4e78-93da-e5db7c07069a
    codebuild:
      project_name: bedrock-agentcore-strands_wa_sec-builder
      execution_role: arn:aws:iam::384612698411:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-67ab493663
      source_bucket: bedrock-agentcore-codebuild-sources-384612698411-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
  strands_aws_api:
    name: strands_aws_api
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::384612698411:role/cloud-optimization-assistant-bedrock-agentcore-runtime-role
      execution_role_auto_create: true
      account: '384612698411'
      region: us-east-1
      ecr_repository: 384612698411.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_aws_api
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: strands_aws_api-SMQ1sVEH8K
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:384612698411:runtime/strands_aws_api-SMQ1sVEH8K
      agent_session_id: ec1aa4dd-1de4-4cff-a7a6-2dbdb3c87b4f
    codebuild:
      project_name: bedrock-agentcore-strands_aws_api-builder
      execution_role: arn:aws:iam::384612698411:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-eb97e4861a
      source_bucket: bedrock-agentcore-codebuild-sources-384612698411-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
  aws_billing_cost_opt:
    name: aws_billing_cost_opt
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::384612698411:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-297fec8e0c
      execution_role_auto_create: false
      account: '384612698411'
      region: us-east-1
      ecr_repository: 384612698411.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aws_billing_cost_opt
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: aws_billing_cost_opt-OWAfhwDzVZ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:384612698411:runtime/aws_billing_cost_opt-OWAfhwDzVZ
      agent_session_id: e5c1c635-9cf5-4a8a-8e62-4c41ad6962f2
    codebuild:
      project_name: bedrock-agentcore-aws_billing_cost_opt-builder
      execution_role: arn:aws:iam::384612698411:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-297fec8e0c
      source_bucket: bedrock-agentcore-codebuild-sources-384612698411-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
